name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            platform: mac
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: win

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript and webpack
        run: npm run build

      - name: Build Electron app (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run dist -- --win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Electron app (macOS)
        if: matrix.os == 'macos-latest'
        run: npm run dist -- --mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Electron app (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npm run dist -- --linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-distributables
          path: |
            release/*.exe
            release/*.dmg
            release/*.pkg
            release/*.AppImage
            release/*.deb
            release/*.snap
            release/*.yml
            release/*.yaml

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" \
            --title "LocalListen ${{ github.ref_name }}" \
            --notes "## LocalListen Release ${{ github.ref_name }}
            
            ### Downloads
            
            #### Windows
            - `LocalListen-Setup-*.exe` - Windows installer
            
            #### macOS
            - `LocalListen-*.dmg` - macOS installer
            - `LocalListen-*.pkg` - Mac App Store package
            
            #### Linux
            - `LocalListen-*.AppImage` - Universal Linux app
            - `LocalListen-*.deb` - Debian/Ubuntu package
            
            ### Installation Instructions
            
            **Windows:** Download and run the .exe installer
            
            **macOS:** Download the .dmg file, open it, and drag LocalListen to Applications
            
            **Linux:** 
            - AppImage: Make executable with `chmod +x` and run
            - DEB: Install with `sudo dpkg -i LocalListen-*.deb`
            
            ### Requirements
            - No FFmpeg installation required - it's bundled!
            - Speaches service for transcription (optional)
            - Ollama service for AI analysis (optional)"

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Upload all artifacts to the release
          find release-artifacts -type f \( -name "*.exe" -o -name "*.dmg" -o -name "*.AppImage" -o -name "*.deb" -o -name "*.zip" \) -exec gh release upload "${{ github.ref_name }}" {} \;